accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('assignmentapp.urls')),
    path('morse/',include('morseapp.urls')),
    path('',include('accounts.urls')),
    path('chicks/',include('chicks.urls')),
    path('diary/',include('diary.urls')),
    path('quiz/',include('quiz.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),
    path('Password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignmentapp/urls.py
from django.urls import path
from . import views
app_name='assignmentapp'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('secret/',views.SecretView.as_view(),name='secret'),
]

chicks/urls.py
from django.urls import path
from . import views
app_name='chicks'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('post/',views.CreateChickView.as_view(),name='post'),
    path('post_done/',views.PostSuccessView.as_view(),name='post_done'),
    path('chicks/<int:category>',views.CategoryView.as_view(),name='chicks_cat'),
    path('user-list/<int:user>',views.UserView.as_view(),name='user_list'),
    path('chicks-detail/<int:pk>',views.DetailView.as_view(),name='chicks_detail'),
    path('mypage/',views.MypageView.as_view(),name='mypage'),
    path('chicks/<int:pk>/delete/',views.ChickDeleteView.as_view(),name='chicks_delete'),
    path('comment/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('comment_detail/<int:pk>',views.redetailView.as_view(),name='comment_detail'),
    path('comment_post/<int:pk>/',views.ChickCommentView.as_view(),name='comment_post'),
    path('category_post/',views.ChickCategoryView.as_view(),name='category_post')
]

quiz/urls.py
from django.urls import path
from . import views
app_name='quiz'

urlpatterns=[
    path('',views.QuizIndexView.as_view(),name="index"),
    path('post_quiz_success/',views.QuizPostSuccessView.as_view(),name="post_quiz_success"),
    path('quiz_mypage/',views.QuizMypageView.as_view(),name="quiz_mypage"),
    path('user_list/<int:user>',views.QuizUserView.as_view(),name='user_list'),
    path('post_quiz/',views.CreateQuizView.as_view(),name="post_quiz"),
    path('quiz/<int:pk>/delete/',views.QuizDeleteView.as_view(),name="quiz_delete"),
    path('quiz_detail/<int:pk>',views.QuizDetailView.as_view(),name='quiz_detail'),
    path('answer_detail/<int:pk>',views.AnswerDetailView.as_view(),name="answer_detail"),
]

chicks/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=30,
    )
    def __str__(self):
        return self.title

class ChickPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )
    title = models.CharField(
        verbose_name='タイトル',
        max_length=50,
    )
    comment = models.TextField(
        verbose_name='コメント',
    )
    image = models.ImageField(
        verbose_name='画像',
        upload_to='images',
        blank=True,
        null=True
    )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True,
    )
    def __str__(self):
        return self.title

class Comment(models.Model):
    comment_user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        ChickPost,
        verbose_name='投稿',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    thoughts_on_comment = models.TextField(
        verbose_name='コメントへの感想',
    )
    comment_image = models.ImageField(
        verbose_name='画像',
        upload_to='images',
        blank=True,
        null=True,
    )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True,
    )
    def __str__(self):
        return self.thoughts_on_comment

chicks/forms.py
from django.forms import ModelForm
from .models import ChickPost,Comment,Category
from django import forms

class ChickPostForm(ModelForm):
    class Meta:
        model=ChickPost
        fields=['category','title','comment','image']

class ChickCommentForm(ModelForm):
    class Meta:
        model=Comment
        fields=['post','thoughts_on_comment','comment_image']

class ChickCategoryForm(ModelForm):
    class Meta:
        model=Category
        fields=['title']

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = \
        'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

chicks/views.py
from django.views import View
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,ListView

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import ChickPostForm,ChickCommentForm,ChickCategoryForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import ChickPost,Comment

from django.views.generic import DetailView

from django.views.generic import DeleteView

from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.views.generic import FormView

class IndexView(ListView):
    template_name="index.html"
    queryset=ChickPost.objects.order_by('-posted_at')
    paginate_by=30

@method_decorator(login_required,name='dispatch')
class CreateChickView(CreateView):
    form_class=ChickPostForm
    template_name="post_chick.html"
    success_url=reverse_lazy('chicks:post_done')
    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name='post_success.html'

@method_decorator(login_required,name='dispatch')
class ChickCommentView(CreateView,View):
    form_class=ChickCommentForm
    template_name='post_chick_comment.html'
    success_url=reverse_lazy('chicks:post_done')
    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["ChickPost"]  = ChickPost.objects.filter(id=pk).first()
        context["Comment"]  = Comment.objects.filter(post=pk)
        context["form"]     = ChickCommentForm
        return render(request,"post_chick_comment.html",context)
    def form_valid(self, form, *args, **kwargs):
        postdata=form.save(commit=False)
        postdata.comment_user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
@method_decorator(login_required,name='dispatch')
class ChickCategoryView(CreateView,View):
    form_class=ChickCategoryForm
    template_name='category_post.html'
    success_url=reverse_lazy('chicks:post_done')
    def get(self, request, *args, **kwargs):
        context = {}
        context["form"]     = ChickCategoryForm
        return render(request,"category_post.html",context)
    def form_valid(self, form, *args, **kwargs):
        postdata=form.save(commit=False)
        postdata.save()
        return super().form_valid(form)

class CategoryView(ListView):
    template_name='index.html'
    paginate_by=30
    def get_queryset(self):
        category_id=self.kwargs['category']
        categories=ChickPost.objects.filter(category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name='index.html'
    paginate_by=30
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=ChickPost.objects.filter(user=user_id).order_by('-posted_at')
        return user_list

class DetailView(DetailView):
    template_name='detail.html'
    model=ChickPost

class redetailView(DetailView):
    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["ChickPost"]=ChickPost.objects.filter(id=pk).first()
        context["Comment"]=Comment.objects.filter(post=pk)
        return render(request,"comment_detail.html",context)

class MypageView(ListView):
    template_name='mypage.html'
    paginate_by=30
    def get_queryset(self):
        queryset=ChickPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

class ChickDeleteView(DeleteView):
    model=ChickPost
    template_name='chicks_delete.html'
    success_url=reverse_lazy('chicks:mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)

class CommentDeleteView(DeleteView):
    model=Comment
    template_name='comment_delete.html'
    success_url=reverse_lazy('chicks:mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)

class ContactView(FormView):
    template_name="contact.html"
    form_class=ContactForm
    success_url=reverse_lazy('chicks:contact')
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = \
            '送信者名:{0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\{3}' \
            .format(name, email, title, message)
        from_email = 'personalcomputer.citrusjunos@gmail.com'
        to_list = ['personalcomputer.citrusjunos@gmail.com']
        message = EmailMessage(subject=subject,body=message,from_email=from_email,to=to_list,)
        message.send()
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

chicks/templates/acontact.html
{% extends 'chicks_base.html' %}
{% load static %}
{% block title %}Chick Contact{% endblock %}
        
    {% block contents %}
    

        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <strong>
                            連絡を取りたいですか？ 以下のフォームに記入してメッセージを送信してください
                        </strong>
                        
                        {% if messages %}
                        <ul class="list-unstyled" style="list-style: none;">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="my-5">
                            <!--method="post"-->
                            <form method="post">
                                {% csrf_token %}
                                {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                {% endfor %}
                                <br>
                                <button type="submit" class="btn btn-primary" id="sendMessageButton">送信</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </main>

    {% endblock %}

chicks/templates/category_post.html
{% extends 'chicks_base.html' %}
{% block title %}Post{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>30文字以内でお願いします</th>
                            <td>{{ form }}</td>
                        </tr>
                        <tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

chicks/templates/chicks_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}chicks{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body style="min-width: 850px; ">
        <div style="background-color: #26d0c9;  text-align: center;">
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center">
                        <li class="nav-item"><a href="{% url 'assignmentapp:index' %}" class="nav-link px-2 text-body-secondary">ホーム</a></li>
                        <li class="nav-item"><a href="{% url 'chicks:index' %}" class="nav-link px-2 text-body-secondary">chicks</a></li>
                        <li class="nav-item"><a href="{% url 'chicks:contact' %}" class="nav-link px-2 text-body-secondary">ご意見・ご要望</a></li>
                        <li class="nav-item"><a href="{% url 'password_reset' %}" class="nav-link px-2 text-body-secondary">パスワードのリセット</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'chicks:mypage' %}" class="nav-link px-2 text-body-secondary">マイページ</a></li>
                        <li class="nav-item"><a href="{% url 'chicks:post' %}" class="nav-link px-2 text-body-secondary">投稿</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link px-2 text-body-secondary">ログアウト</a></li>
                        <li class="nav-item"><a href="{% url 'chicks:category_post' %}" class="nav-link px-2 text-body-secondary">カテゴリー登録</a></li>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link px-2 text-body-secondary">ログイン</a></li>
                        {% endif %}
                    </ul>
                </footer>
            </div>
        </div>
        
        {% block contents %}{% endblock %}
        
        <div style="display: flex; align-items: flex-end; background-color: #2f5167; color:#fff;height: 120px;">
            <small style="margin-left: auto;">&copy; 2023.citrus.junos</small>
        </div>
    </body>
    </html>

chicks/templates/chicks_delete.html
{% extends 'chicks_base.html' %}
{% block title %}Chicks Delete{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除していいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">削除</button>
                    <a href="{% url 'chicks:chicks_detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

chicks/templates/comment_detail.html
{% extends 'chicks_base.html' %}
{% block title %}Comment Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{ChickPost.title}}</h2>
                <p>{{ChickPost.comment}}</p>
                <br>
                <p>{{ChickPost.posted_at}}に投稿</p>
                {% if ChickPost.image %}
                <p><img src="{{ ChickPost.image.url }}" style="max-width: 200px;"></p>
                {% endif %}
                {% if request.user == ChickPost.user %}
                    <form method="POST">
                        <a href="{% url 'chicks:chicks_delete' ChickPost.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
                <p>{{ChickPost.user}}</p>
            </div>
        </div>
    </div>
    <br>
    <h3 style="text-align: center;">{{ Comment|length }}件のコメント</h3>
    <br>
    {% for num in Comment %}
    <hr>
        <div class="container">
                <div class="row">
                    <div class="col offset-3">
                        <p>ID No.{{num.id}}</p>
                        <p>{{num.thoughts_on_comment}}</p>
                        <br>
                        <p>{{num.posted_at}}に投稿</p>
                        {% if num.comment_image %}
                        <p><img src="{{ num.comment_image.url }}" style="max-width: 200px;"></p>
                        {% endif %}
                        <p>{{Comment.comment_image}}</p>
                        {% if request.user == num.comment_user %}
                            <form method="POST">
                                <a href="{% url 'chicks:comment_delete' num.pk %}" class="btn btn-primary my-2">削除する</a>
                            </form>
                        {% endif %}
                        {{ num.comment_user }}
                    </div>
                </div>
            </div>
            {% empty %}
            <div style="text-align: center;">リプライはありません。</div>
            {% endfor %}
            {% if user.is_authenticated %}
            <div class="container">
                <div class="row">
                    <div class="col offset-3">
                        <button type="button" class="btn btn-primary my-2" onclick="location.href='{% url 'chicks:comment_post' ChickPost.id %}'">コメントする</button>
                    </div>
                </div>
            </div>            
            {% endif %}
        </div>
    </div>
    {% endblock %}

chicks/templates/detail.html
{% extends 'chicks_base.html' %}
{% block title %}Chicks Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{object.title}}</h2>
                <p>{{object.comment}}</p>
                <br>
                <p>{{object.posted_at}}に投稿</p>
                {% if object.image %}
                <p><img src="{{ object.image.url }}" style="max-width: 200px;"></p>
                {% endif %}
                {% if request.user == object.user %}
                    <form method="POST">
                        <a href="{% url 'chicks:chicks_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

chicks/templates/display_list.html
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            {% if record.image %}
              <img src="{{ record.image.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>
            {% endif %}
            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'chicks:chicks_detail' record.id %}'">コメントなし</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'chicks:comment_detail' record.id %}'">コメントあり</button>
                  {% if user.is_authenticated %}
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'chicks:comment_post' record.id %}'">コメントする</button>
                  {% endif %}
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'chicks:chicks_cat' category=record.category.id %}'">{{ record.category.title }}</button>
                </div>
                <a style="text-decoration: none;" href="{% url 'chicks:user_list' user=record.user.id %}"><small class="text-muted">{{ record.user.username }}</small></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

chicks/templates/display_title.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">chicks</h1>
        <!--たぶん要らない↓-->
        <!--<p class="lead text-muted"></p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'chicks:post' %}" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>-->
      </div>
    </div>
  </section>

chicks/templates/index.html
{% extends 'chicks_base.html' %}
{% load static %}
{% block title %}chicks{% endblock %}

    {% block contents %}
    {% include "display_title.html" %}
    {% include "display_list.html" %}
    {% include "pagination.html" %}
    {% endblock %}

chicks/templates/mypage.html
{% extends 'chicks_base.html' %}
{% block title %}Mypage{% endblock %}
    {% block contents %}
    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'chicks:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}
    {% include "display_list.html" %}
    {% include "pagination.html" %}
    {% endblock %}

chicks/templates/pagination.html
<ul class="pagination" style="justify-content: center;">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{{ page_obj.previous_page_numbber }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

chicks/templates/post_chick.html
{% extends 'chicks_base.html' %}
{% block title %}Post{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>タイトル</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>画像</th>
                            <td>{{ form.image }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

chicks/templates/post_chick_comment.html
{% extends 'chicks_base.html' %}
{% block title %}Post Comment{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{ChickPost.title}}</h2>
                <p>{{ChickPost.comment}}</p>
                <br>
                <p>{{ChickPost.posted_at}}に投稿</p>
                {% if ChickPost.image %}
                <p><img src="{{ ChickPost.image.url }}" style="max-width: 200px;"></p>
                {% endif %}
                {% if request.user == ChickPost.user %}
                    <form method="POST">
                        <a href="{% url 'chicks:chicks_delete' ChickPost.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
                <p>{{ChickPost.user}}</p>
            </div>
        </div>
    </div>
    <br>
    <h3 style="text-align: center;">{{ Comment|length }}件のコメント</h3>
    <br>
    {% for num in Comment %}
    <hr>
        <div class="container">
                <div class="row">
                    <div class="col offset-3">
                        <p>ID No.{{num.id}}</p>
                        <p>{{num.thoughts_on_comment}}</p>
                        <br>
                        <p>{{num.posted_at}}に投稿</p>
                        {% if num.comment_image %}
                        <p><img src="{{ num.comment_image.url }}" style="max-width: 200px;"></p>
                        {% endif %}
                        {% if request.user == num.comment_user %}
                            <form method="POST">
                                <a href="{% url 'chicks:comment_delete' num.pk %}" class="btn btn-primary my-2">削除する</a>
                            </form>
                        {% endif %}
                        {{ num.comment_user }}
                    </div>
                </div>
            </div>
            {% empty %}
            <div style="text-align: center;">リプライはありません。</div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>対象</th>
                            <td>{{ form.post}}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.thoughts_on_comment}}</td>
                        </tr>
                        <tr>
                            <th>画像</th>
                            <td>{{ form.comment_image }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

chicks/templates/post_success.html
{% extends 'chicks_base.html' %}
{% block title %}Post Success{% endblock %}
    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました</h4>
                <a href="{% url 'chicks:index' %}" class="btn btn-secondary my-2">chicks</a>
            </div>
        </div>
    </div>
    {% endblock %}