assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('assignmentapp.urls')),
    path('morse/',include('morseapp.urls')),
    path('',include('accounts.urls')),
    path('chicks/',include('chicks.urls')),
    path('diary/',include('diary.urls')),
    path('quiz/',include('quiz.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),
    path('Password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignmentapp/urls.py
from django.urls import path
from . import views
app_name='assignmentapp'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('secret/',views.SecretView.as_view(),name='secret'),
]

morseapp/urls.py
from django.urls import path
from . import views
#from .views import nippo
app_name='morseapp'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('japanese_language_change_morse/',views.JLMorseView.as_view(),name="japanese_language_change_morse"),
    path('morse_change_japanese_language/',views.MorseJLView.as_view(),name="morse_change_japanese_language"),
    path('alphabet_change_morse/',views.AlphabetMorseView.as_view(),name="alphabet_change_morse"),
    path('morse_change_alphabet/',views.MorseAlphabetView.as_view(),name="morse_change_alphabet"),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('japanese_language/',views.JLView.as_view(),name="japanese_language"),
    path('alphabet/',views.AlphabetView.as_view(),name="alphabet"),
]

quiz/urls.py
from django.urls import path
from . import views
app_name='quiz'

urlpatterns=[
    path('',views.QuizIndexView.as_view(),name="index"),
    path('post_quiz_success/',views.QuizPostSuccessView.as_view(),name="post_quiz_success"),
    path('quiz_mypage/',views.QuizMypageView.as_view(),name="quiz_mypage"),
    path('user_list/<int:user>',views.QuizUserView.as_view(),name='user_list'),
    path('post_quiz/',views.CreateQuizView.as_view(),name="post_quiz"),
    path('quiz/<int:pk>/delete/',views.QuizDeleteView.as_view(),name="quiz_delete"),
    path('quiz_detail/<int:pk>',views.QuizDetailView.as_view(),name='quiz_detail'),
    path('answer_detail/<int:pk>',views.AnswerDetailView.as_view(),name="answer_detail"),
]

morseapp/models.py
from django.db import models

morseapp/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse_lazy
from .form import ContactForm

from django.contrib import messages
from django.core.mail import EmailMessage

from django.views.generic.base import TemplateView

import random

class IndexView(TemplateView):
    template_name="morse_index.html"
    def post(self, request, *args, **kwargs):
        if request.POST:
            message=""
            url=""
            go=""
            img=""
            num = random.randint(1,12)
            #switchが欲しい
            if num == 1:
                message="何で押したん？"
            if num == 2:
                message="押したくなるよね"
            if num == 3:
                message="何回も押すなよ"
            if num == 4:
                n = random.randint(1,3)
                go='押してみな飛ぶぞ{}'.format(n)
                if n==1:
                    url='https://www.yahoo.co.jp/'
                if n==2:
                    url='https://www.amazon.co.jp/'
                if n==3:
                    url='https://www.youtube.com/'
            if num == 5:
                img="../static/images/book_fukayomi.png"
            if num == 6:
                message="しかし何も起こらなかった"
            context = {
                'coment': message,
                'website': url,
                "go": go,
                'img':img,
            }
        return render(request, IndexView.template_name, context)

"""class TestView(TemplateView):
    template_name="test.html"
    message=""
    def post(self, request, *args, **kwargs):
        messagepost=JLMorseView.message
        if request.POST:
            messagepost = request.POST["name1"]
            messageget=messagepost
            context = {
            'messagepost': messagepost,
            'messageget': messageget,
        }
        return render(request, TestView.template_name, context)"""

class JLMorseView(TemplateView):
    template_name="japanese_language_change_morse.html"
    message=""
 
    def post(self, request, *args, **kwargs):
        messagepost=JLMorseView.message
        if request.POST:
            messagepost = request.POST["name1"]
            
            messageget=messagepost
            name=list(messageget)
            x=len(name)
            n=0
            i=0
            moji=['あ','い','う','え','お',
                  'か','き','く','け','こ',
                  'さ','し','す','せ','そ',
                  'た','ち','つ','て','と',
                  'な','に','ぬ','ね','の',
                  'は','ひ','ふ','へ','ほ',
                  'ま','み','む','め','も',
                  'や','ゆ','よ',
                  'ら','り','る','れ','ろ',
                  'わ','を','ん',
                  'が','ぎ','ぐ','げ','ご',
                  'ざ','じ','ず','ぜ','ぞ',
                  'だ','ぢ','づ','で','ど',
                  'ば','び','ぶ','べ','ぼ',
                  'ぱ','ぴ','ぷ','ぺ','ぽ',
                  '、','。','ー',]
            morse = ['ーー・ーー', '・ー', '・・ー', 'ー・ーーー', '・ー・・・',#あ行
                     '・ー・・', 'ー・ー・・', '・・・ー', 'ー・ーー', 'ーーーー',#か行
                     'ー・ー・ー', 'ーー・ー・', 'ーーー・ー', '・ーーー・', 'ーーー・',#さ行
                     'ー・', '・・ー・', '・ーー・', '・ー・ーー', '・・ー・・',#た行
                     '・ー・', 'ー・ー・', '・・・・', 'ーー・ー', '・・ーー',#な行
                     'ー・・・', 'ーー・・ー', 'ーー・・', '・', 'ー・・',#は行
                     'ー・・ー', '・・ー・ー', 'ー', 'ー・・・ー', 'ー・・ー・',#ま行
                     '・ーー', 'ー・・ーー', 'ーー',#や行
                     '・・・', 'ーー・', 'ー・ーー・', 'ーーー', '・ー・ー',#ら行
                     'ー・ー', '・ーーー', '・ー・ー・',#わ行
                     '・ー・・,・・', 'ー・ー・・,・・', '・・・ー,・・', 'ー・ーー,・・', 'ーーーー,・・',#が行
                     'ー・ー・ー,・・', 'ーー・ー・,・・', 'ーーー・ー,・・', '・ーーー・,・・', 'ーーー・,・・',#ざ行
                     'ー・,・・', '・・ー・,・・', '・ーー・,・・', '・ー・ーー,・・', '・・ー・・,・・',#だ行
                     'ー・・・,・・', 'ーー・・ー,・・', 'ーー・・,・・', '・,・・', 'ー・・,・・',#ば行
                     'ー・・・,・・ーー・', 'ーー・・ー,・・ーー・', 'ーー・・,・・ーー・,・・ーー・', '・,・・ーー・', 'ー・・,・・ーー・',#ぱ行
                     '・ー・ー・ー', '', '・ーー・ー',]
            r=[]
            for i in range(x):#while i<=x:
                for n in range(72):#while n <= 60:
                    if(name[i]==moji[n]):
                        r.append(morse[n])
                        r.append(',')
                    n+=1
                i=i+1
            l=''.join(r)
            messageget=l
        context = {
            'messagepost': messagepost,
            'messageget': messageget,
        }
        return render(request, JLMorseView.template_name, context)

class MorseJLView(TemplateView):
    template_name="morse_change_japanese_language.html"
    message=""
 
    def post(self, request, *args, **kwargs):
        messagepost=MorseJLView.message
        if request.POST:
            messagepost = request.POST["name1"]
            messageget=messagepost
            morse = ['ーー・ーー', '・ー', '・・ー', 'ー・ーーー', '・ー・・・',#あ行
                     '・ー・・', 'ー・ー・・', '・・・ー', 'ー・ーー', 'ーーーー',#か行
                     'ー・ー・ー', 'ーー・ー・', 'ーーー・ー', '・ーーー・', 'ーーー・',#さ行
                     'ー・', '・・ー・', '・ーー・', '・ー・ーー', '・・ー・・',#た行
                     '・ー・', 'ー・ー・', '・・・・', 'ーー・ー', '・・ーー',#な行
                     'ー・・・', 'ーー・・ー', 'ーー・・', '・', 'ー・・',#は行
                     'ー・・ー', '・・ー・ー', 'ー', 'ー・・・ー', 'ー・・ー・',#ま行
                     '・ーー', 'ー・・ーー', 'ーー',#や行
                     '・・・', 'ーー・', 'ー・ーー・', 'ーーー', '・ー・ー',#ら行
                     'ー・ー', '・ーーー', '・ー・ー・',#わ行
                     '・ー・・,・・', 'ー・ー・・,・・', '・・・ー,・・', 'ー・ーー,・・', 'ーーーー,・・',#が行
                     'ー・ー・ー,・・', 'ーー・ー・,・・', 'ーーー・ー,・・', '・ーーー・,・・', 'ーーー・,・・',#ざ行
                     'ー・,・・', '・・ー・,・・', '・ーー・,・・', '・ー・ーー,・・', '・・ー・・,・・',#だ行
                     'ー・・・,・・', 'ーー・・ー,・・', 'ーー・・,・・', '・,・・', 'ー・・,・・',#ば行
                     'ー・・・,・・ーー・', 'ーー・・ー,・・ーー・', 'ーー・・,・・ーー・,・・ーー・', '・,・・ーー・', 'ー・・,・・ーー・',#ぱ行
                     '・ー・ー・ー', '', '・ーー・ー',]
            moji=['あ','い','う','え','お',
                  'か','き','く','け','こ',
                  'さ','し','す','せ','そ',
                  'た','ち','つ','て','と',
                  'な','に','ぬ','ね','の',
                  'は','ひ','ふ','へ','ほ',
                  'ま','み','む','め','も',
                  'や','ゆ','よ',
                  'ら','り','る','れ','ろ',
                  'わ','を','ん',
                  'が','ぎ','ぐ','げ','ご',
                  'ざ','じ','ず','ぜ','ぞ',
                  'だ','ぢ','づ','で','ど',
                  'ば','び','ぶ','べ','ぼ',
                  'ぱ','ぴ','ぷ','ぺ','ぽ',
                  '、','。','ー',]
            
            name=list(messageget)
            name.append(',')
            x=len(name)
            ja=[]
            n=0
            d=0
            for p in range(x):
                if name[p]==',':
                    d=d+1
            for f in range(d):
                r=[]
                while name[n]!=',':
                    r.append(name[n])
                    n=n+1
                r=''.join(r)
                if name[n] ==',':
                    n=n+1
                for i in range(72):
                    if r==morse[i]:
                        ja.append(moji[i])

            l=''.join(ja)
            messageget=l
        context = {
            'messagepost': messagepost,
            'messageget': messageget,
        }
        return render(request, MorseJLView.template_name, context)

class AlphabetMorseView(TemplateView):
    template_name="alphabet_change_morse.html"
    message=""
 
    def post(self, request, *args, **kwargs):
        messagepost=AlphabetMorseView.message
        if request.POST:
            messagepost = request.POST["name1"]
            
            messageget=messagepost
            morse=['・ー','ー・・・','ー・ー・','ー・・','・',#ABCDE
                   '・・ー・','ーー・','・・・・','・・','・ーーー',#FGHIJ
                   'ー・－','・ー・・','ーー','ー・','ーーー',#KLMNO
                   '・ーー・','ーー・ー','・ー・','・・・','ー',#PQRST
                   '・・ー','・・・ー','・ーー','ー・・ー','ー・ーー',#UVWXY
                   'ーー・・',]#Z
            moji=['a','b','c','d','e',
                  'f','j','h','i','j',
                  'k','l','m','n','o',
                  'p','q','r','s','t',
                  'u','v','w','x','y',
                  'z',]
            MOJI=['A','B','C','D','E',
                  'F','G','H','I','J',
                  'K','L','M','N','O',
                  'P','Q','R','S','T',
                  'U','V','W','X','Y',
                  'Z',]
            name=messageget
            name=list(name)
            x=len(name)
            n=0
            i=0
            r=[]
            for i in range(x):
                for n in range(26):
                    if(name[i]==moji[n] or name[i]==MOJI[n]):
                        r.append(morse[n])
                        r.append(',')
                    n+=1
                i=i+1
            l=''.join(r)
            messageget=l
        context = {
            'messagepost': messagepost,
            'messageget': messageget,
        }
        return render(request, AlphabetMorseView.template_name, context)

class MorseAlphabetView(TemplateView):
    template_name="morse_change_alphabet.html"
    message=""
 
    def post(self, request, *args, **kwargs):
        messagepost=MorseAlphabetView.message
        if request.POST:
            messagepost = request.POST["name1"]
            
            messageget=messagepost
            morse=['・ー','ー・・・','ー・ー・','ー・・','・',#ABCDE
                   '・・ー・','ーー・','・・・・','・・','・ーーー',#FGHIJ
                   'ー・－','・ー・・','ーー','ー・','ーーー',#KLMNO
                   '・ーー・','ーー・ー','・ー・','・・・','ー',#PQRST
                   '・・ー','・・・ー','・ーー','ー・・ー','ー・ーー',#UVWXY
                   'ーー・・',]#Z
            moji=['a','b','c','d','e',
                  'f','j','h','i','j',
                  'k','l','m','n','o',
                  'p','q','r','s','t',
                  'u','v','w','x','y',
                  'z',]
            """MOJI=['A','B','C','D','E',
                  'F','G','H','I','J',
                  'K','L','M','N','O',
                  'P','Q','R','S','T',

morseapp/templates/acontact.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}
        
    {% block contents %}
    

        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <strong>
                            連絡を取りたいですか？ 以下のフォームに記入してメッセージを送信してください
                        </strong>
                        
                        {% if messages %}
                        <ul class="list-unstyled" style="list-style: none;">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="my-5">
                            <!--method="post"-->
                            <form method="post">
                                {% csrf_token %}
                                {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                {% endfor %}
                                <br>
                                <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </main>

    {% endblock %}

morseapp/templates/alphabet.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>アルファベットをモールス信号にモールス信号をアルファベットにするよ</p>
                <p>※アルファベットは半角でお願いします</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="">
                        <label>入力</label>
                        <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                    </div>
                    <input type="submit" value="変換">
                </form>
            </div>
            <div>
                <form action="" method="POST">
                    <div class="">
                        <label>出力</label>
                        <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/alphabet_change_morse.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>アルファベットからモールス信号に変えるよ</p>
                <p>※アルファベットは半角でお願いします</p>
                <div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <label>入力</label>
                            <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                        </div>
                        <input type="submit" value="変換">
                    </form>
                </div>
                <div>
                    <form action="" method="POST">
                        <div class="">
                            <label>出力</label>
                            <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/japanese_language.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}
    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>ひらがなをモールス信号にモールス信号をひらがなにするよ</p>
                <p>濁点と半濁点は無理</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="">
                        <label>入力</label>
                        <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                    </div>
                    <input type="submit" value="変換">
                </form>
            </div>
            <div>
                <form action="" method="POST">
                    <div class="">
                        <label>出力</label>
                        <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/japanese_language_change_morse.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>ひらがなからモールス信号に変えるよ</p>
                <div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <label>入力</label>
                            <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                        </div>
                        <input type="submit" value="変換">
                    </form>
                </div>
                <div>
                    <form action="" method="POST">
                        <div class="">
                            <label>出力</label>
                            <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/morse_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body style="min-width: 850px; ">
        <div style="background-color: #26d0c9;  text-align: center;">
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center">
                        <li class="nav-item"><a href="{% url 'assignmentapp:index' %}" class="nav-link px-2 text-body-secondary">ホーム</a></li>
                        <li class="nav-item"><a href="{% url 'morseapp:index' %}" class="nav-link px-2 text-body-secondary">morse</a></li>
                        <li class="nav-item"><a href="{% url 'morseapp:contact' %}" class="nav-link px-2 text-body-secondary">ご意見・ご要望</a></li>
                        <li class="nav-item"><a href="{% url 'morseapp:japanese_language' %}" class="nav-link px-2 text-body-secondary">ひらがな</a></li>
                        <li class="nav-item"><a href="{% url 'morseapp:alphabet' %}" class="nav-link px-2 text-body-secondary">アルファベット</a></li>
                    </ul>
                </footer>
            </div>
        </div>
        
        {% block contents %}{% endblock %}
        
        <div style="display: flex; align-items: flex-end; background-color: #2f5167; color:#fff;min-height: 120px;">
            <s style="padding: 10px;">
                <a style="text-decoration: none;"class="" href="{% url 'morseapp:japanese_language_change_morse' %}">ひらがなからモールス信号に変換</a>
            </s>
            <s style="padding: 10px;">
                <a style="text-decoration: none;"class="" href="{% url 'morseapp:morse_change_japanese_language' %}">モールス信号からひらがなに変換</a>
            </s>
            <s style="padding: 10px;">
                <a style="text-decoration: none;"class="" href="{% url 'morseapp:alphabet_change_morse' %}">アルファベットからモールス信号に変換</a>
            </s>
            <s style="padding: 10px;">
                <a style="text-decoration: none;"class="" href="{% url 'morseapp:morse_change_alphabet' %}">モールス信号からアルファベットに変換</a>
            </s>
            <small style="margin-left: auto;">&copy; 2023.citrus.junos</small>
        </div>
    </body>
    </html>

morseapp/templates/morse_change_alphabet.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>モールス信号からアルファベットに変えるよ</p>
                <div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <label>入力</label>
                            <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                        </div>
                        <input type="submit" value="変換">
                    </form>
                </div>
                <div>
                    <form action="" method="POST">
                        <div class="">
                            <label>出力</label>
                            <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/morse_change_japanese_language.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>モールス信号からひらがなに変えるよ</p>
                <div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="">
                            <label>入力</label>
                            <textarea name="name1" cols="40" rows="10" placeholder="メッセージを入力してください" class="form-control" required id="name1" style="height: 204px;">{{ messagepost }}</textarea>
                        </div>
                        <input type="submit" value="変換">
                    </form>
                </div>
                <div>
                    <form action="" method="POST">
                        <div class="">
                            <label>出力</label>
                            <textarea name="name2" cols="40" rows="10" placeholder="こちらには入力しないでください" class="form-control" required id="name2" style="height: 204px;">{{ messageget }}</textarea>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

morseapp/templates/morse_index.html
{% extends 'morse_base.html' %}
{% load static %}
{% block title %}{% endblock %}

    {% block contents %}

    <div style="background-size: 100px; height: 300px; background-image: url({{ img }})">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="">
                        <p>上にあるやつを選んでねー</p>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="ボタン">
                        </form>
                        <p>{{ coment }}</p>
                        <a href="{{ website }}"style="text-decoration: none;">{{ go }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}