accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('assignmentapp.urls')),
    path('morse/',include('morseapp.urls')),
    path('',include('accounts.urls')),
    path('chicks/',include('chicks.urls')),
    path('diary/',include('diary.urls')),
    path('quiz/',include('quiz.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),
    path('Password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignmentapp/urls.py
from django.urls import path
from . import views
app_name='assignmentapp'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('secret/',views.SecretView.as_view(),name='secret'),
]

diary/urls.py
from django.urls import path
from . import views
app_name='diary'

urlpatterns=[
    path('',views.DiaryIndexView.as_view(),name='diary'),
    path('post/',views.CreateChickView.as_view(),name='post'),
    path('post_done/',views.PostSuccessView.as_view(),name='post_done'),
    #path('chicks/<int:category>',views.CategoryView.as_view(),name='chicks_cat'),
    path('user-list/<int:user>',views.UserView.as_view(),name='user_list'),
    path('diary-detail/<int:pk>',views.DetailView.as_view(),name='diary_detail'),
    path('diary_mypage/',views.DiaryMypageView.as_view(),name='diary_mypage'),
    path('diary/<int:pk>/delete/',views.ChickDeleteView.as_view(),name='diary_delete'),
    path('diarygood/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='diarygood_delete'),
    path('diarygood_detail/<int:pk>',views.redetailView.as_view(),name='diarygood_detail'),
    path('diarygood_post/<int:pk>/',views.ChickCommentView.as_view(),name='diarygood_post'),
    #path('category_post/',views.ChickCategoryView.as_view(),name='category_post')
]

quiz/urls.py
from django.urls import path
from . import views
app_name='quiz'

urlpatterns=[
    path('',views.QuizIndexView.as_view(),name="index"),
    path('post_quiz_success/',views.QuizPostSuccessView.as_view(),name="post_quiz_success"),
    path('quiz_mypage/',views.QuizMypageView.as_view(),name="quiz_mypage"),
    path('user_list/<int:user>',views.QuizUserView.as_view(),name='user_list'),
    path('post_quiz/',views.CreateQuizView.as_view(),name="post_quiz"),
    path('quiz/<int:pk>/delete/',views.QuizDeleteView.as_view(),name="quiz_delete"),
    path('quiz_detail/<int:pk>',views.QuizDetailView.as_view(),name='quiz_detail'),
    path('answer_detail/<int:pk>',views.AnswerDetailView.as_view(),name="answer_detail"),
]

quiz/models.py
from django.db import models

from accounts.models import CustomUser

class Category(models.Model):
    category=models.CharField(
        verbose_name='カテゴリー',
        max_length=50,
    )
    def __str__(self):
        return self.category

class Quiz(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリー',
        on_delete=models.CASCADE,
    )
    quiz = models.TextField(
        verbose_name='問題文',
    )
    answer = models.TextField(
        verbose_name='答え',
    )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True,
    )
    def __str__(self):
        return self.quiz

quiz/forms.py
from django.forms import ModelForm
from .models import Quiz

class QuizForm(ModelForm):
    class Meta:
        model=Quiz
        fields=['category','quiz','answer']

quiz/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from .models import Quiz

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import QuizForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.views.generic import DetailView
from django.views.generic import DeleteView

class QuizIndexView(ListView):
    template_name="quiz.html"
    queryset=Quiz.objects.order_by('-posted_at')
    paginate_by=30

class QuizPostSuccessView(TemplateView):
    template_name='quiz_post_success.html'

class QuizUserView(ListView):
    template_name='quiz.html'
    paginate_by=30
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=Quiz.objects.filter(user=user_id).order_by('-posted_at')
        return user_list

class QuizMypageView(ListView):
    template_name='quiz_mypage.html'
    paginate_by=30
    def get_queryset(self):
        queryset=Quiz.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

@method_decorator(login_required,name='dispatch')
class CreateQuizView(CreateView):
    form_class=QuizForm
    template_name="post_quiz.html"
    success_url=reverse_lazy('quiz:post_quiz_success')
    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
class QuizDeleteView(DeleteView):
    model=Quiz
    template_name='quiz_delete.html'
    success_url=reverse_lazy('quiz:quiz_mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)
    
class QuizDetailView(DetailView):
    template_name='quiz_detail.html'
    model=Quiz

class AnswerDetailView(DetailView):
    template_name='answer_detail.html'
    model=Quiz

quiz/templates/answer_detail.html
{% extends 'quiz_base.html' %}
{% block title %}quiz Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{object.category}}</h2>
                <p>{{object.quiz}}</p>
                <br>
                <p>{{object.answer}}</p>
                <br>
                <p>{{object.posted_at}}に投稿</p>
                <form method="POST">
                    <a href="{% url 'quiz:index' %}" class="btn btn-primary my-2">quiz</a>
                </form>
                {% if request.user == object.user %}
                    <form method="POST">
                        <a href="{% url 'quiz:quiz_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

quiz/templates/post_category_quiz.html
{% extends 'quiz_base.html' %}
{% block title %}Post{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>50文字以内でお願いします</th>
                            <td>{{ form }}</td>
                        </tr>
                        <tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

quiz/templates/post_quiz.html
{% extends 'quiz_base.html' %}
{% block title %}Post{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>問題</th>
                            <td>{{ form.quiz }}</td>
                        </tr>
                        <tr>
                            <th>答え</th>
                            <td>{{ form.answer }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

quiz/templates/quiz.html
{% extends 'quiz_base.html' %}
{% load static %}
{% block title %}quiz{% endblock %}

    {% block contents %}
    {% include "quiz_display_title.html" %}
    {% include "quiz_display_list.html" %}
    {% include "quiz_pagination.html" %}
    {% endblock %}

quiz/templates/quiz_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}quiz{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body style="min-width: 850px; ">
        <div style="background-color: #26d0c9;  text-align: center;">
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center">
                        <li class="nav-item"><a href="{% url 'assignmentapp:index' %}" class="nav-link px-2 text-body-secondary">ホーム</a></li>
                        <li class="nav-item"><a href="{% url 'quiz:index' %}" class="nav-link px-2 text-body-secondary">quiz</a></li>
                        <li class="nav-item"><a href="{% url 'assignmentapp:contact' %}" class="nav-link px-2 text-body-secondary">ご意見・ご要望</a></li>
                        <li class="nav-item"><a href="{% url 'password_reset' %}" class="nav-link px-2 text-body-secondary">パスワードのリセット</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link px-2 text-body-secondary">ログアウト</a></li>
                        <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary">なし</a></li>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link px-2 text-body-secondary">ログイン</a></li>
                        {% endif %}
                    </ul>
                </footer>
            </div>
        </div>
        
        {% block contents %}{% endblock %}
        
        <div style="display: flex; align-items: flex-end; background-color: #2f5167; color:#fff;height: 120px;">
            <small style="margin-left: auto;">&copy; 2023.citrus.junos</small>
        </div>
    </body>
    </html>

quiz/templates/quiz_delete.html
{% extends 'quiz_base.html' %}
{% block title %}quiz Delete{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除していいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">削除</button>
                    <a href="{% url 'quiz:quiz_detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

quiz/templates/quiz_detail.html
{% extends 'quiz_base.html' %}
{% block title %}quiz Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{object.category}}</h2>
                <p>{{object.quiz}}</p>
                <br>
                <p>{{object.posted_at}}に投稿</p>
                <form method="POST">
                    <a href="{% url 'quiz:answer_detail' object.pk %}" class="btn btn-primary my-2">答えを見る</a>
                </form>
                <br>
                {% if request.user == object.user %}
                    <form method="POST">
                        <a href="{% url 'quiz:quiz_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

quiz/templates/quiz_display_list.html
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{record.quiz|truncatechars:15}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'quiz:quiz_detail' record.id %}'">チャレンジ</button>
                </div>
                <a style="text-decoration: none;" href="{% url 'quiz:user_list' user=record.user.id %}"><small class="text-muted">{{ record.user.username }}</small></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

quiz/templates/quiz_display_title.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">quiz</h1>
        <a href="{% url 'quiz:post_quiz' %}" class="btn btn-primary my-2">投稿する</a>
      </div>
    </div>
  </section>

quiz/templates/quiz_index.html
{% extends 'quiz_base.html' %}
{% load static %}
{% block title %}quiz{% endblock %}

    {% block contents %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">工事中</h1>
            <p style="opacity:0.03;">出来てない</p>
          </div>
        </div>
      </section>
    {% endblock %}

quiz/templates/quiz_mypage.html
{% extends 'quiz_base.html' %}
{% block title %}Mypage{% endblock %}
    {% block contents %}
    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'diary:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}
    {% include "quiz_display_list.html" %}
    {% include "quiz_pagination.html" %}
    {% endblock %}

quiz/templates/quiz_pagination.html
<ul class="pagination" style="justify-content: center;">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{{ page_obj.previous_page_numbber }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

quiz/templates/quiz_post_success.html
{% extends 'quiz_base.html' %}
{% block title %}Post Success{% endblock %}
    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました</h4>
                <a href="{% url 'quiz:index' %}" class="btn btn-secondary my-2">quiz</a>
            </div>
        </div>
    </div>
    {% endblock %}