accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

assignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('assignmentapp.urls')),
    path('morse/',include('morseapp.urls')),
    path('',include('accounts.urls')),
    path('chicks/',include('chicks.urls')),
    path('diary/',include('diary.urls')),
    path('quiz/',include('quiz.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),
    path('Password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignmentapp/urls.py
from django.urls import path
from . import views
app_name='assignmentapp'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('secret/',views.SecretView.as_view(),name='secret'),
]

diary/urls.py
from django.urls import path
from . import views
app_name='diary'

urlpatterns=[
    path('',views.DiaryIndexView.as_view(),name='diary'),
    path('post/',views.CreateChickView.as_view(),name='post'),
    path('post_done/',views.PostSuccessView.as_view(),name='post_done'),
    #path('chicks/<int:category>',views.CategoryView.as_view(),name='chicks_cat'),
    path('user-list/<int:user>',views.UserView.as_view(),name='user_list'),
    path('diary-detail/<int:pk>',views.DetailView.as_view(),name='diary_detail'),
    path('diary_mypage/',views.DiaryMypageView.as_view(),name='diary_mypage'),
    path('diary/<int:pk>/delete/',views.ChickDeleteView.as_view(),name='diary_delete'),
    path('diarygood/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='diarygood_delete'),
    path('diarygood_detail/<int:pk>',views.redetailView.as_view(),name='diarygood_detail'),
    path('diarygood_post/<int:pk>/',views.ChickCommentView.as_view(),name='diarygood_post'),
    #path('category_post/',views.ChickCategoryView.as_view(),name='category_post')
]

quiz/urls.py
from django.urls import path
from . import views
app_name='quiz'

urlpatterns=[
    path('',views.QuizIndexView.as_view(),name="index"),
    path('post_quiz_success/',views.QuizPostSuccessView.as_view(),name="post_quiz_success"),
    path('quiz_mypage/',views.QuizMypageView.as_view(),name="quiz_mypage"),
    path('user_list/<int:user>',views.QuizUserView.as_view(),name='user_list'),
    path('post_quiz/',views.CreateQuizView.as_view(),name="post_quiz"),
    path('quiz/<int:pk>/delete/',views.QuizDeleteView.as_view(),name="quiz_delete"),
    path('quiz_detail/<int:pk>',views.QuizDetailView.as_view(),name='quiz_detail'),
    path('answer_detail/<int:pk>',views.AnswerDetailView.as_view(),name="answer_detail"),
]

diary/models.py
from django.db import models

from accounts.models import CustomUser

class Diary(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        verbose_name='タイトル',
        max_length=100,
    )
    sentence = models.TextField(
        verbose_name='文章',
    )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True,
    )
    def __str__(self):
        return self.title

class DiaryGood(models.Model):
    good_user= models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Diary,
        verbose_name='投稿',
        on_delete=models.CASCADE,
    )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True,
    )
    def __int__(self):
        return self.post

diary/forms.py
from django.forms import ModelForm
from .models import Diary,DiaryGood
from django import forms

class DiaryForm(ModelForm):
    class Meta:
        model=Diary
        fields=['title','sentence']

class DiaryGoodForm(ModelForm):
    class Meta:
        model=DiaryGood
        fields=['post']

diary/views.py
from django.views import View
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,ListView

from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import DiaryForm,DiaryGoodForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Diary,DiaryGood

from django.views.generic import DetailView

from django.views.generic import DeleteView


class DiaryIndexView(ListView):
    template_name="diary.html"
    queryset=Diary.objects.order_by('-posted_at')
    paginate_by=30

@method_decorator(login_required,name='dispatch')
class CreateChickView(CreateView):
    form_class=DiaryForm
    template_name="post_diary.html"
    success_url=reverse_lazy('diary:post_done')
    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name='diary_post_success.html'

@method_decorator(login_required,name='dispatch')
class ChickCommentView(CreateView,View):
    form_class=DiaryGoodForm
    template_name='post_diarygood.html'
    success_url=reverse_lazy('diary:post_done')
    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["ChickPost"]  = Diary.objects.filter(id=pk).first()
        context["Comment"]  = DiaryGood.objects.filter(post=pk)
        context["form"]     = DiaryGoodForm
        return render(request,"post_diarygood.html",context)
    def form_valid(self, form):
        postdata=form.save(commit=False)
        postdata.good_user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
class UserView(ListView):
    template_name='diary.html'
    paginate_by=30
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=Diary.objects.filter(user=user_id).order_by('-posted_at')
        return user_list

class DetailView(DetailView):
    template_name='diary_detail.html'
    model=Diary

class redetailView(DetailView):
    def get(self, request, pk, *args, **kwargs):
        context = {}
        context["ChickPost"]=Diary.objects.filter(id=pk).first()
        context["Comment"]=DiaryGood.objects.filter(post=pk)
        return render(request,"diarygood_detail.html",context)

class DiaryMypageView(ListView):
    template_name='diary_mypage.html'
    paginate_by=30
    def get_queryset(self):
        queryset=Diary.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

class ChickDeleteView(DeleteView):
    model=Diary
    template_name='diary_delete.html'
    success_url=reverse_lazy('diary:diary_mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)

class CommentDeleteView(DeleteView):
    model=DiaryGood
    template_name='diarygood_delete.html'
    success_url=reverse_lazy('diary:diary_mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)

diary/templates/diary.html
{% extends 'diary_base.html' %}
{% load static %}
{% block title %}diary{% endblock %}

    {% block contents %}
    {% include "diary_display_title.html" %}
    {% include "diary_display_list.html" %}
    {% include "diary_pagination.html" %}
    {% endblock %}

diary/templates/diary_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}assignment{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body style="min-width: 850px; ">
        <div style="background-color: #26d0c9;  text-align: center;">
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center">
                        <li class="nav-item"><a href="{% url 'assignmentapp:index' %}" class="nav-link px-2 text-body-secondary">ホーム</a></li>
                        <li class="nav-item"><a href="{% url 'diary:diary' %}" class="nav-link px-2 text-body-secondary">diary</a></li>
                        <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary"></a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'diary:diary_mypage'%}" class="nav-link px-2 text-body-secondary">マイページ</a></li>
                        <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary"></a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link px-2 text-body-secondary">ログアウト</a></li>
                        <li class="nav-item"><a href="" class="nav-link px-2 text-body-secondary"></a></li>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link px-2 text-body-secondary">ログイン</a></li>
                        {% endif %}
                    </ul>
                </footer>
            </div>
        </div>
        
        {% block contents %}{% endblock %}
        
        <div style="display: flex; align-items: flex-end; background-color: #2f5167; color:#fff;height: 120px;">
            <small style="margin-left: auto;">&copy; 2023.citrus.junos</small>
        </div>
    </body>
    </html>

diary/templates/diary_delete.html
{% extends 'diary_base.html' %}
{% block title %}Chicks Delete{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除していいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">削除</button>
                    <a href="{% url 'diary:diary_detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

diary/templates/diary_detail.html
{% extends 'diary_base.html' %}
{% block title %}Chicks Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{object.title}}</h2>
                <p>{{object.sentence}}</p>
                <br>
                <p>{{object.posted_at}}に投稿</p>
                {% if object.image %}
                <p><img src="{{ object.image.url }}" style="max-width: 200px;"></p>
                {% endif %}
                {% if request.user == object.user %}
                    <form method="POST">
                        <a href="{% url 'diary:diary_delete' object.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

diary/templates/diary_display_list.html
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            {% if object.image %}
              <img src="{{ object.image.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg>
            {% endif %}
            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'diary:diary_detail' record.id %}'">いいねなし</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'diary:diarygood_detail' record.id %}'">いいねあり</button>
                  {% if user.is_authenticated %}
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'diary:diarygood_post' record.id %}'">いいねする</button>
                  {% endif %}
                </div>
                <a style="text-decoration: none;" href="{% url 'diary:user_list' user=record.user.id %}"><small class="text-muted">{{ record.user.username }}</small></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

diary/templates/diary_display_title.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">diary(整備中)</h1>
        <a href="{% url 'diary:post' %}" class="btn btn-primary my-2">投稿する</a>
      </div>
    </div>
  </section>

diary/templates/diary_mypage.html
{% extends 'diary_base.html' %}
{% block title %}Mypage{% endblock %}
    {% block contents %}
    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'diary:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}
    {% include "diary_display_list.html" %}
    {% include "diary_pagination.html" %}
    {% endblock %}

diary/templates/diary_pagination.html
<ul class="pagination" style="justify-content: center;">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{{ page_obj.previous_page_numbber }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

diary/templates/diary_post_success.html
{% extends 'diary_base.html' %}
{% block title %}Post Success{% endblock %}
    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました</h4>
            </div>
        </div>
    </div>
    {% endblock %}

diary/templates/diarygood_delete.html
{% extends 'diary_base.html' %}
{% block title %}Chicks Delete{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除していいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">削除</button>
                    <a href="{% url 'diary:diarygood_detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

diary/templates/diarygood_detail.html
{% extends 'diary_base.html' %}
{% block title %}Comment Datail{% endblock %}
    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{ChickPost.title}}</h2>
                <p>{{ChickPost.sentence}}</p>
                <br>
                <p>{{ChickPost.posted_at}}に投稿</p>
                {% if ChickPost.image %}
                <p><img src="{{ ChickPost.image.url }}" style="max-width: 200px;"></p>
                {% endif %}
                {% if request.user == ChickPost.user %}
                    <form method="POST">
                        <a href="{% url 'diary:diary_delete' ChickPost.pk %}" class="btn btn-primary my-2">削除する</a>
                    </form>
                {% endif %}
                <p>{{ChickPost.user}}</p>
            </div>
        </div>
    </div>
    <br>
    <h3 style="text-align: center;">{{ Comment|length }}件のいいね</h3>
    <br>
            {% if user.is_authenticated %}
            <div class="container">
                <div class="row">
                    <div class="col offset-3">
                        <button type="button" class="btn btn-primary my-2" onclick="location.href='{% url 'diary:diarygood_post' ChickPost.id %}'">いいねする</button>
                    </div>
                </div>
            </div>            
            {% endif %}
        </div>
    </div>
    {% endblock %}

diary/templates/post_diary.html
{% extends 'diary_base.html' %}
{% block title %}Post{% endblock %}
    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>タイトル</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.sentence }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

diary/templates/post_diarygood.html
{% extends 'diary_base.html' %}
{% block title %}diary{% endblock %}
{% block contents %}
<div class="container">
<div class="row">
    <div class="col offset-3">
        <h2>{{ChickPost.title}}</h2>
        <p>{{ChickPost.sentence}}</p>
        <br>
        <p>{{ChickPost.posted_at}}に投稿</p>
        {% if ChickPost.image %}
        <p><img src="{{ ChickPost.image.url }}" style="max-width: 200px;"></p>
        {% endif %}
        {% if request.user == ChickPost.user %}
        <form method="POST">
            <a href="{% url 'diary:diary_delete' ChickPost.pk %}" class="btn btn-primary my-2">削除する</a>
        </form>
        {% endif %}
        <p>{{ChickPost.user}}</p>
    </div>
</div>
</div>
<br>
<h3 style="text-align: center;">{{ Comment|length }}件のいいね</h3>
<br>
</div>
</div>
<hr>
<br>
<div class="container">
    <div class="row">
        <div class="col offset-2">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>対象</th>
                        <td>{{form.post}}</td>
                    </tr>
                </table>
                <hr>
                <button type="submit">投稿する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}